#cloud-config
yum_repos:
    beegfs:
        name: Beegfs on Linux
        baseurl: https://www.beegfs.io/release/beegfs_6/dists/rhel7
        enabled: true
        metadata_expire: 7d
        gpgcheck: false

packages:
  - git
  - pciutils
  - unzip
  - beegfs-storage
  - kernel-devel
  - gcc
  - beegfs-client
  - beegfs-helperd
  - beegfs-utils

users:
  - name: ${sudoer_username}
    groups: adm, wheel, systemd-journal
    homedir: /${sudoer_username}
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
%{ for key in ssh_authorized_keys ~}
      - ${key}
%{ endfor ~}

runcmd:
  - restorecon -R /${sudoer_username}
  - "(echo -e '\nHostKeyAlgorithms ssh-rsa\n' >> /etc/ssh/sshd_config && systemctl restart sshd)"
  - yum upgrade -y
  - sed -i 's/crashkernel=auto/crashkernel=no/' /etc/default/grub
  - sed -i 's/GRUB_CMDLINE_LINUX="[^"]*/& nouveau.modeset=0 rd.driver.blacklist=nouveau/' /etc/default/grub
  - grub2-mkconfig -o /boot/grub2/grub.cfg
  # Remove all ifcfg configuration files that have no corresponding network interface in ip link show.
  - for i in /etc/sysconfig/network-scripts/ifcfg-*; do if ! ip link show | grep -q "$${i##*-}:"; then rm -f $i; fi; done
  - if [ "${node_name}" != "login1" ]; then mkdir -p /mnt/beegfs_storage && /opt/beegfs/sbin/beegfs-setup-storage -p /mnt/beegfs_storage -s "${node_id}" -i "${node_id}01" -m "${puppetmaster_ip}"; sed -i "/^storeAllowFirstRunInit/c\storeAllowFirstRunInit=true" /etc/beegfs/beegfs-storage.conf;systemctl start beegfs-storage;else rm -f /etc/beegfs/beegfs-storage.conf;yum remove beegfs-storage;  fi;
  - /opt/beegfs/sbin/beegfs-setup-client -m ${puppetmaster_ip}
  - sed -i "/^sysMountSanityCheckMS/c\sysMountSanityCheckMS=0" /etc/beegfs/beegfs-client.conf


write_files:
  - content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ${puppetmaster_ip} mgmt1
      ${puppetmaster_ip} puppet
    path: /etc/hosts
    permissions: "0644"
  - content: |
      facts : {
        blocklist : [ "EC2" ],
      }
    path: /etc/puppetlabs/facter/facter.conf
    permissions: "0644"
  - content: |
      ---
      custom_attributes:
        1.2.840.113549.1.9.7: "${puppetmaster_password}"
    path: /etc/puppetlabs/puppet/csr_attributes.yaml
    permissions: "0640"

disable_ec2_metadata: false
timezone: "UTC"
fqdn: "${node_name}"
output: { all: "| tee -a /var/log/cloud-init-output.log" }
power_state:
  delay: now
  mode: reboot
